drop table if exists PLAYER;
create table PLAYER(ID BIGINT, IS_GUEST TINYINT, NICK_NAME VARCHAR(20) COLLATE utf8_unicode_ci, ROLE_TYPE INT default 0, COMPANION_ROLE_TYPE INT, GUID VARCHAR(32) COLLATE utf8_unicode_ci, DEVICE_ID VARCHAR(63) COLLATE utf8_unicode_ci, DATA_SYNC_TIME BIGINT, PET_ID INT, CLOTH VARCHAR(255) COLLATE utf8_unicode_ci, APPEAR_PROP VARCHAR(255) COLLATE utf8_unicode_ci, STAR_REWARD INT, ENERGY BIGINT, ENERGY_TIME BIGINT, PACKAGE_INFO TEXT COLLATE utf8_unicode_ci, CHECKPOINT_INFO TEXT COLLATE utf8_unicode_ci, GEM INT, SIGN_INFO VARCHAR(255) COLLATE utf8_unicode_ci, OTHER_INFO VARCHAR(64) COLLATE utf8_unicode_ci, CREATE_TIME BIGINT, PRIMARY KEY (ID));

drop table if exists CHECKPOINT_DATA;
create table CHECKPOINT_DATA(ID BIGINT, USER_ID BIGINT, CHECKPOINT_ID INT, SUM_SCORE BIGINT, SUM_TIME BIGINT, SUM_STAR INT, FAIL_TIME INT, HIGH_SCORE INT, SUM_GAME_TIME BIGINT, HIGH_GAME_TIME INT, PRIMARY KEY (ID));

drop table if exists OPERATOR;
create table OPERATOR(ID BIGINT, USER_ID BIGINT, OPERATOR_ID INT, INFO VARCHAR(1024) COLLATE utf8_unicode_ci, PRIMARY KEY (ID));

drop table if exists ERROR;
create table ERROR(ID BIGINT, USER_ID BIGINT, ERROR_CODE INT, ERROR_INFO VARCHAR(1024) COLLATE utf8_unicode_ci, PRIMARY KEY (ID));

drop table if exists IDS;
create table IDS(ID BIGINT, MIN BIGINT default 1, CURRENT BIGINT default 1, PRIMARY KEY (ID));


insert into IDS values(3,1,1);
insert into IDS values(1,1,1);
insert into IDS values(2,1,1);