ALTER TABLE T_COMPANY ADD COLUMN TEST_BOOL TINYINT after VALID_TERM;
ALTER TABLE T_COMPANY ADD COLUMN TEST_FLOAT FLOAT after TEST_BOOL;
ALTER TABLE T_COMPANY ADD COLUMN TEST_DOUBLE DOUBLE after TEST_FLOAT;
ALTER TABLE T_COMPANY ADD COLUMN TEST_INT INT after TEST_DOUBLE;
drop table T_CUSTOM_SBH;
drop table T_FOLLOW_RECORD_SBH;
drop table T_SMS_RECORD_SBH;
